apiVersion: v1
kind: Service
metadata:
  name: {{ include "test-app-api.fullname" . }}
  labels:
    {{- include "test-app-api.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: api-http-port
      protocol: TCP
      name: api-http-port-svc
  selector:
    {{- include "test-app-api.selectorLabels" . | nindent 4 }}